import { CreateUserDto } from 'src/users/dto';
import { Role } from 'src/users/entities';

export const dummyUsers : CreateUserDto[] = [
  {
    rut: '17647021-6',
    name: 'Martina',
    surname: 'Carvajal',
    email: 'martina@mail.com',
    password: 'Password1!',
    country: 'Chile',
    phone: 56987654321,
    role: Role.ADMIN,
  },
  {
    rut: '19683298-k',
    name: 'Sebastián',
    surname: 'González',
    email: 'sebastian@mail.com',
    password: 'SecurePass2!',
    country: 'Chile',
    phone: 56998765432,
    role: Role.ADMIN,
  },
  {
    rut: '10019870-3',
    name: 'Isabella',
    surname: 'Fuentes',
    email: 'isabella@mail.com',
    password: 'Password1!',
    country: 'Chile',
    phone: 56987654323,
    role: Role.USER,
  },
  {
    rut: '9217673-8',
    name: 'Joaquín',
    surname: 'Morales',
    email: 'joaquin@mail.com',
    password: 'Password1!',
    country: 'Chile',
    phone: 56976543210,
    role: Role.USER,
  },
  {
    rut: '20274694-2',
    name: 'Catalina',
    surname: 'Rojas',
    email: 'catalina@mail.com',
    password: 'Password1!',
    country: 'Chile',
    phone: 56965432109,
    role: Role.USER,
  },
  {
    rut: '8073045-4',
    name: 'Vicente',
    surname: 'Martínez',
    email: 'vicente@mail.com',
    password: 'Password1!',
    country: 'Chile',
    phone: 56954321098,
    role: Role.USER,
  },
];
